language: java
jdk:
- oraclejdk8
env:
  global:
  - GH_REF=github.com/bme-db-lab/opencypher-tck-tests
  - secure: BZp1RaHnR/pG3yNairDrTqoSBrX/9d44o78RlD+azD/fxBCXaYewrcgcFBswhzhpqHV9OZiYfM4ohRIaK/LD8fcr+182LsuoY5tMKdL19bgYg/kHIWIC7IhF80ekT0z9soH7jWJJGvRSW03bYwjcICbKIysDJMg3sHaO+wffuDkT70hvhxC4ti4vaHjWbAwr/vPmZ9cfHI/Cw414TqPBMhCwmnDlcFnVuYKPYJhEIoWXBgwMAW2BfBejjASfFRcnul7sfOegsqIK91ty9FLG0xwaYEmqUvU1Z2NlQF6IOSmtHyJcH9x2Xq1xhS+dxagdYJSiqDSx8tK3QYoC0At1SNOk5L70GDfZpAreYAajBaoSxCh7NUfY47JKg+6gkuUqdiXopZImHG5tP3c5ork3gu+2N9b9TmF6I1GwWovf7YT7NyuAQn1WBo43ER7RKYwfHAscqvk5Aw/cdUsNDORwXqfQTJ5CWyQi6n4UvxrJyasv8kEyLw8RsPadl7UX1efLrlKbwbutaGm8Js6Jao7Rmn8xgepqBMzWgfzBrLfYByAERqZFlM1sKiDto8thnAQIFcO6gS/NIFXLQwyNyzteIRckm9iDZug7JxP6EIGfSz/ah/gc2ZfQLWzsS2FDs79Snj5N3/F5wpgOATaFmHoPY1JUlzbNibbrBIeVIQlCO4o=
script:
- ./gradlew build -x test
- ./gradlew cucumberTest -Dlog4j.configurationFile=log4j2.xml --stacktrace || true
- ./deploy.sh
notifications:
  slack: ftsrg:1cgKhTwTbPgsK0MdAJBtYKTT
  email: false
  on_success: change
  on_failure: always
