/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Backwards Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getBackwardsRelationship()
 * @model
 * @generated
 */
public interface BackwardsRelationship extends DirectedRelationship
{
} // BackwardsRelationship
