/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsFactory
 * @model kind="package"
 * @generated
 */
public interface FeatureResultsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "featureResults";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.cucumber.ingraph/featureresult/FeatureResults";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "featureResults";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FeatureResultsPackage eINSTANCE = ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl.init();

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ListElementImpl <em>List Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.ListElementImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getListElement()
   * @generated
   */
  int LIST_ELEMENT = 17;

  /**
   * The number of structural features of the '<em>List Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.ValueImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getValue()
   * @generated
   */
  int VALUE = 0;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = LIST_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.NodeImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getNode()
   * @generated
   */
  int NODE = 1;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.NodeDescImpl <em>Node Desc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.NodeDescImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getNodeDesc()
   * @generated
   */
  int NODE_DESC = 2;

  /**
   * The feature id for the '<em><b>Labels</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DESC__LABELS = NODE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Property Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DESC__PROPERTY_MAP = NODE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Node Desc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DESC_FEATURE_COUNT = NODE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.RelationshipImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 3;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.RelationshipDescImpl <em>Relationship Desc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.RelationshipDescImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getRelationshipDesc()
   * @generated
   */
  int RELATIONSHIP_DESC = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_DESC__TYPE = RELATIONSHIP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Property Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_DESC__PROPERTY_MAP = RELATIONSHIP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Relationship Desc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_DESC_FEATURE_COUNT = RELATIONSHIP_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PathImpl <em>Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.PathImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPath()
   * @generated
   */
  int PATH = 5;

  /**
   * The number of structural features of the '<em>Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PathBodyImpl <em>Path Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.PathBodyImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPathBody()
   * @generated
   */
  int PATH_BODY = 6;

  /**
   * The feature id for the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_BODY__NODE = PATH_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Path Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_BODY__PATH_LINKS = PATH_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Path Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_BODY_FEATURE_COUNT = PATH_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PathLinkImpl <em>Path Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.PathLinkImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPathLink()
   * @generated
   */
  int PATH_LINK = 7;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_LINK__RELATIONSHIP = 0;

  /**
   * The feature id for the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_LINK__NODE = 1;

  /**
   * The number of structural features of the '<em>Path Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATH_LINK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.DirectedRelationshipImpl <em>Directed Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.DirectedRelationshipImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getDirectedRelationship()
   * @generated
   */
  int DIRECTED_RELATIONSHIP = 8;

  /**
   * The feature id for the '<em><b>Relationship</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTED_RELATIONSHIP__RELATIONSHIP = 0;

  /**
   * The number of structural features of the '<em>Directed Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTED_RELATIONSHIP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ForwardsRelationshipImpl <em>Forwards Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.ForwardsRelationshipImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getForwardsRelationship()
   * @generated
   */
  int FORWARDS_RELATIONSHIP = 9;

  /**
   * The feature id for the '<em><b>Relationship Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARDS_RELATIONSHIP__RELATIONSHIP_DESC = 0;

  /**
   * The number of structural features of the '<em>Forwards Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARDS_RELATIONSHIP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.BackwardsRelationshipImpl <em>Backwards Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.BackwardsRelationshipImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getBackwardsRelationship()
   * @generated
   */
  int BACKWARDS_RELATIONSHIP = 10;

  /**
   * The feature id for the '<em><b>Relationship Desc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARDS_RELATIONSHIP__RELATIONSHIP_DESC = 0;

  /**
   * The number of structural features of the '<em>Backwards Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARDS_RELATIONSHIP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.IntegerImpl <em>Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.IntegerImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getInteger()
   * @generated
   */
  int INTEGER = 11;

  /**
   * The number of structural features of the '<em>Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.FloatingPointImpl <em>Floating Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.FloatingPointImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getFloatingPoint()
   * @generated
   */
  int FLOATING_POINT = 12;

  /**
   * The number of structural features of the '<em>Floating Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOATING_POINT_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.BoolImpl <em>Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.BoolImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getBool()
   * @generated
   */
  int BOOL = 13;

  /**
   * The number of structural features of the '<em>Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.NullValueImpl <em>Null Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.NullValueImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getNullValue()
   * @generated
   */
  int NULL_VALUE = 14;

  /**
   * The number of structural features of the '<em>Null Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.ListImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getList()
   * @generated
   */
  int LIST = 15;

  /**
   * The feature id for the '<em><b>List Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__LIST_CONTENTS = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ListContentsImpl <em>List Contents</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.ListContentsImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getListContents()
   * @generated
   */
  int LIST_CONTENTS = 16;

  /**
   * The feature id for the '<em><b>List Contents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_CONTENTS__LIST_CONTENTS = 0;

  /**
   * The number of structural features of the '<em>List Contents</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_CONTENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.MapImpl <em>Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.MapImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getMap()
   * @generated
   */
  int MAP = 18;

  /**
   * The number of structural features of the '<em>Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PropertyMapImpl <em>Property Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.PropertyMapImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPropertyMap()
   * @generated
   */
  int PROPERTY_MAP = 19;

  /**
   * The feature id for the '<em><b>Map Contents</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_MAP__MAP_CONTENTS = MAP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Property Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_MAP_FEATURE_COUNT = MAP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.MapContentsImpl <em>Map Contents</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.MapContentsImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getMapContents()
   * @generated
   */
  int MAP_CONTENTS = 20;

  /**
   * The feature id for the '<em><b>Key Value Pairs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_CONTENTS__KEY_VALUE_PAIRS = 0;

  /**
   * The number of structural features of the '<em>Map Contents</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_CONTENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.KeyValuePairImpl <em>Key Value Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.KeyValuePairImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getKeyValuePair()
   * @generated
   */
  int KEY_VALUE_PAIR = 21;

  /**
   * The number of structural features of the '<em>Key Value Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY_VALUE_PAIR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PropertyValueImpl <em>Property Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.PropertyValueImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPropertyValue()
   * @generated
   */
  int PROPERTY_VALUE = 22;

  /**
   * The number of structural features of the '<em>Property Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_VALUE_FEATURE_COUNT = KEY_VALUE_PAIR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link ingraph.cucumber.featureresult.featureResults.impl.MyStringImpl <em>My String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ingraph.cucumber.featureresult.featureResults.impl.MyStringImpl
   * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getMyString()
   * @generated
   */
  int MY_STRING = 23;

  /**
   * The number of structural features of the '<em>My String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_STRING_FEATURE_COUNT = VALUE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.NodeDesc <em>Node Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Desc</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.NodeDesc
   * @generated
   */
  EClass getNodeDesc();

  /**
   * Returns the meta object for the attribute list '{@link ingraph.cucumber.featureresult.featureResults.NodeDesc#getLabels <em>Labels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Labels</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.NodeDesc#getLabels()
   * @see #getNodeDesc()
   * @generated
   */
  EAttribute getNodeDesc_Labels();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.NodeDesc#getPropertyMap <em>Property Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property Map</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.NodeDesc#getPropertyMap()
   * @see #getNodeDesc()
   * @generated
   */
  EReference getNodeDesc_PropertyMap();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc <em>Relationship Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship Desc</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.RelationshipDesc
   * @generated
   */
  EClass getRelationshipDesc();

  /**
   * Returns the meta object for the attribute '{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getType()
   * @see #getRelationshipDesc()
   * @generated
   */
  EAttribute getRelationshipDesc_Type();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getPropertyMap <em>Property Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Property Map</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getPropertyMap()
   * @see #getRelationshipDesc()
   * @generated
   */
  EReference getRelationshipDesc_PropertyMap();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Path <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Path
   * @generated
   */
  EClass getPath();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.PathBody <em>Path Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Body</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PathBody
   * @generated
   */
  EClass getPathBody();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.PathBody#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Node</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PathBody#getNode()
   * @see #getPathBody()
   * @generated
   */
  EReference getPathBody_Node();

  /**
   * Returns the meta object for the containment reference list '{@link ingraph.cucumber.featureresult.featureResults.PathBody#getPathLinks <em>Path Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Path Links</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PathBody#getPathLinks()
   * @see #getPathBody()
   * @generated
   */
  EReference getPathBody_PathLinks();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.PathLink <em>Path Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Path Link</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PathLink
   * @generated
   */
  EClass getPathLink();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.PathLink#getRelationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relationship</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PathLink#getRelationship()
   * @see #getPathLink()
   * @generated
   */
  EReference getPathLink_Relationship();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.PathLink#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Node</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PathLink#getNode()
   * @see #getPathLink()
   * @generated
   */
  EReference getPathLink_Node();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.DirectedRelationship <em>Directed Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Directed Relationship</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.DirectedRelationship
   * @generated
   */
  EClass getDirectedRelationship();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.DirectedRelationship#getRelationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relationship</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.DirectedRelationship#getRelationship()
   * @see #getDirectedRelationship()
   * @generated
   */
  EReference getDirectedRelationship_Relationship();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.ForwardsRelationship <em>Forwards Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forwards Relationship</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.ForwardsRelationship
   * @generated
   */
  EClass getForwardsRelationship();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.ForwardsRelationship#getRelationshipDesc <em>Relationship Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relationship Desc</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.ForwardsRelationship#getRelationshipDesc()
   * @see #getForwardsRelationship()
   * @generated
   */
  EReference getForwardsRelationship_RelationshipDesc();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.BackwardsRelationship <em>Backwards Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backwards Relationship</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.BackwardsRelationship
   * @generated
   */
  EClass getBackwardsRelationship();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.BackwardsRelationship#getRelationshipDesc <em>Relationship Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Relationship Desc</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.BackwardsRelationship#getRelationshipDesc()
   * @see #getBackwardsRelationship()
   * @generated
   */
  EReference getBackwardsRelationship_RelationshipDesc();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Integer <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Integer
   * @generated
   */
  EClass getInteger();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.FloatingPoint <em>Floating Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Floating Point</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.FloatingPoint
   * @generated
   */
  EClass getFloatingPoint();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Bool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Bool
   * @generated
   */
  EClass getBool();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.NullValue <em>Null Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Null Value</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.NullValue
   * @generated
   */
  EClass getNullValue();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the containment reference list '{@link ingraph.cucumber.featureresult.featureResults.List#getListContents <em>List Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List Contents</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.List#getListContents()
   * @see #getList()
   * @generated
   */
  EReference getList_ListContents();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.ListContents <em>List Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Contents</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.ListContents
   * @generated
   */
  EClass getListContents();

  /**
   * Returns the meta object for the containment reference list '{@link ingraph.cucumber.featureresult.featureResults.ListContents#getListContents <em>List Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List Contents</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.ListContents#getListContents()
   * @see #getListContents()
   * @generated
   */
  EReference getListContents_ListContents();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.ListElement <em>List Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Element</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.ListElement
   * @generated
   */
  EClass getListElement();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.Map <em>Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.Map
   * @generated
   */
  EClass getMap();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.PropertyMap <em>Property Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Map</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PropertyMap
   * @generated
   */
  EClass getPropertyMap();

  /**
   * Returns the meta object for the containment reference '{@link ingraph.cucumber.featureresult.featureResults.PropertyMap#getMapContents <em>Map Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Map Contents</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PropertyMap#getMapContents()
   * @see #getPropertyMap()
   * @generated
   */
  EReference getPropertyMap_MapContents();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.MapContents <em>Map Contents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Contents</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.MapContents
   * @generated
   */
  EClass getMapContents();

  /**
   * Returns the meta object for the containment reference list '{@link ingraph.cucumber.featureresult.featureResults.MapContents#getKeyValuePairs <em>Key Value Pairs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Key Value Pairs</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.MapContents#getKeyValuePairs()
   * @see #getMapContents()
   * @generated
   */
  EReference getMapContents_KeyValuePairs();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.KeyValuePair <em>Key Value Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Key Value Pair</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.KeyValuePair
   * @generated
   */
  EClass getKeyValuePair();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.PropertyValue <em>Property Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Value</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.PropertyValue
   * @generated
   */
  EClass getPropertyValue();

  /**
   * Returns the meta object for class '{@link ingraph.cucumber.featureresult.featureResults.MyString <em>My String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My String</em>'.
   * @see ingraph.cucumber.featureresult.featureResults.MyString
   * @generated
   */
  EClass getMyString();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FeatureResultsFactory getFeatureResultsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.ValueImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.NodeImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.NodeDescImpl <em>Node Desc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.NodeDescImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getNodeDesc()
     * @generated
     */
    EClass NODE_DESC = eINSTANCE.getNodeDesc();

    /**
     * The meta object literal for the '<em><b>Labels</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_DESC__LABELS = eINSTANCE.getNodeDesc_Labels();

    /**
     * The meta object literal for the '<em><b>Property Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_DESC__PROPERTY_MAP = eINSTANCE.getNodeDesc_PropertyMap();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.RelationshipImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.RelationshipDescImpl <em>Relationship Desc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.RelationshipDescImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getRelationshipDesc()
     * @generated
     */
    EClass RELATIONSHIP_DESC = eINSTANCE.getRelationshipDesc();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP_DESC__TYPE = eINSTANCE.getRelationshipDesc_Type();

    /**
     * The meta object literal for the '<em><b>Property Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP_DESC__PROPERTY_MAP = eINSTANCE.getRelationshipDesc_PropertyMap();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PathImpl <em>Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.PathImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPath()
     * @generated
     */
    EClass PATH = eINSTANCE.getPath();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PathBodyImpl <em>Path Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.PathBodyImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPathBody()
     * @generated
     */
    EClass PATH_BODY = eINSTANCE.getPathBody();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_BODY__NODE = eINSTANCE.getPathBody_Node();

    /**
     * The meta object literal for the '<em><b>Path Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_BODY__PATH_LINKS = eINSTANCE.getPathBody_PathLinks();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PathLinkImpl <em>Path Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.PathLinkImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPathLink()
     * @generated
     */
    EClass PATH_LINK = eINSTANCE.getPathLink();

    /**
     * The meta object literal for the '<em><b>Relationship</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_LINK__RELATIONSHIP = eINSTANCE.getPathLink_Relationship();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATH_LINK__NODE = eINSTANCE.getPathLink_Node();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.DirectedRelationshipImpl <em>Directed Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.DirectedRelationshipImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getDirectedRelationship()
     * @generated
     */
    EClass DIRECTED_RELATIONSHIP = eINSTANCE.getDirectedRelationship();

    /**
     * The meta object literal for the '<em><b>Relationship</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTED_RELATIONSHIP__RELATIONSHIP = eINSTANCE.getDirectedRelationship_Relationship();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ForwardsRelationshipImpl <em>Forwards Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.ForwardsRelationshipImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getForwardsRelationship()
     * @generated
     */
    EClass FORWARDS_RELATIONSHIP = eINSTANCE.getForwardsRelationship();

    /**
     * The meta object literal for the '<em><b>Relationship Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORWARDS_RELATIONSHIP__RELATIONSHIP_DESC = eINSTANCE.getForwardsRelationship_RelationshipDesc();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.BackwardsRelationshipImpl <em>Backwards Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.BackwardsRelationshipImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getBackwardsRelationship()
     * @generated
     */
    EClass BACKWARDS_RELATIONSHIP = eINSTANCE.getBackwardsRelationship();

    /**
     * The meta object literal for the '<em><b>Relationship Desc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BACKWARDS_RELATIONSHIP__RELATIONSHIP_DESC = eINSTANCE.getBackwardsRelationship_RelationshipDesc();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.IntegerImpl <em>Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.IntegerImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getInteger()
     * @generated
     */
    EClass INTEGER = eINSTANCE.getInteger();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.FloatingPointImpl <em>Floating Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.FloatingPointImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getFloatingPoint()
     * @generated
     */
    EClass FLOATING_POINT = eINSTANCE.getFloatingPoint();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.BoolImpl <em>Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.BoolImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getBool()
     * @generated
     */
    EClass BOOL = eINSTANCE.getBool();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.NullValueImpl <em>Null Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.NullValueImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getNullValue()
     * @generated
     */
    EClass NULL_VALUE = eINSTANCE.getNullValue();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.ListImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>List Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__LIST_CONTENTS = eINSTANCE.getList_ListContents();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ListContentsImpl <em>List Contents</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.ListContentsImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getListContents()
     * @generated
     */
    EClass LIST_CONTENTS = eINSTANCE.getListContents();

    /**
     * The meta object literal for the '<em><b>List Contents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_CONTENTS__LIST_CONTENTS = eINSTANCE.getListContents_ListContents();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.ListElementImpl <em>List Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.ListElementImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getListElement()
     * @generated
     */
    EClass LIST_ELEMENT = eINSTANCE.getListElement();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.MapImpl <em>Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.MapImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getMap()
     * @generated
     */
    EClass MAP = eINSTANCE.getMap();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PropertyMapImpl <em>Property Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.PropertyMapImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPropertyMap()
     * @generated
     */
    EClass PROPERTY_MAP = eINSTANCE.getPropertyMap();

    /**
     * The meta object literal for the '<em><b>Map Contents</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_MAP__MAP_CONTENTS = eINSTANCE.getPropertyMap_MapContents();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.MapContentsImpl <em>Map Contents</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.MapContentsImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getMapContents()
     * @generated
     */
    EClass MAP_CONTENTS = eINSTANCE.getMapContents();

    /**
     * The meta object literal for the '<em><b>Key Value Pairs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_CONTENTS__KEY_VALUE_PAIRS = eINSTANCE.getMapContents_KeyValuePairs();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.KeyValuePairImpl <em>Key Value Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.KeyValuePairImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getKeyValuePair()
     * @generated
     */
    EClass KEY_VALUE_PAIR = eINSTANCE.getKeyValuePair();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.PropertyValueImpl <em>Property Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.PropertyValueImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getPropertyValue()
     * @generated
     */
    EClass PROPERTY_VALUE = eINSTANCE.getPropertyValue();

    /**
     * The meta object literal for the '{@link ingraph.cucumber.featureresult.featureResults.impl.MyStringImpl <em>My String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ingraph.cucumber.featureresult.featureResults.impl.MyStringImpl
     * @see ingraph.cucumber.featureresult.featureResults.impl.FeatureResultsPackageImpl#getMyString()
     * @generated
     */
    EClass MY_STRING = eINSTANCE.getMyString();

  }

} //FeatureResultsPackage
