/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Floating Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.FloatingPoint#getValue <em>Value</em>}</li>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.FloatingPoint#isIsInfinity <em>Is Infinity</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getFloatingPoint()
 * @model
 * @generated
 */
public interface FloatingPoint extends FeatureValue
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(BigDecimal)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getFloatingPoint_Value()
   * @model
   * @generated
   */
  BigDecimal getValue();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.FloatingPoint#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(BigDecimal value);

  /**
   * Returns the value of the '<em><b>Is Infinity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Infinity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Infinity</em>' attribute.
   * @see #setIsInfinity(boolean)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getFloatingPoint_IsInfinity()
   * @model
   * @generated
   */
  boolean isIsInfinity();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.FloatingPoint#isIsInfinity <em>Is Infinity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Infinity</em>' attribute.
   * @see #isIsInfinity()
   * @generated
   */
  void setIsInfinity(boolean value);

} // FloatingPoint
