/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Forwards Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getForwardsRelationship()
 * @model
 * @generated
 */
public interface ForwardsRelationship extends DirectedRelationship
{
} // ForwardsRelationship
