/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.Integer#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getInteger()
 * @model
 * @generated
 */
public interface Integer extends FeatureValue
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getInteger_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.Integer#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // Integer
