/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.List#getListContents <em>List Contents</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getList()
 * @model
 * @generated
 */
public interface List extends FeatureValue
{
  /**
   * Returns the value of the '<em><b>List Contents</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List Contents</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Contents</em>' containment reference.
   * @see #setListContents(ListContents)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getList_ListContents()
   * @model containment="true"
   * @generated
   */
  ListContents getListContents();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.List#getListContents <em>List Contents</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Contents</em>' containment reference.
   * @see #getListContents()
   * @generated
   */
  void setListContents(ListContents value);

} // List
