/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Contents</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.ListContents#getListContents <em>List Contents</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getListContents()
 * @model
 * @generated
 */
public interface ListContents extends EObject
{
  /**
   * Returns the value of the '<em><b>List Contents</b></em>' containment reference list.
   * The list contents are of type {@link ingraph.cucumber.featureresult.featureResults.ListElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Contents</em>' containment reference list.
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getListContents_ListContents()
   * @model containment="true"
   * @generated
   */
  EList<ListElement> getListContents();

} // ListContents
