/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Map Contents</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.MapContents#getKeyValuePairs <em>Key Value Pairs</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getMapContents()
 * @model
 * @generated
 */
public interface MapContents extends EObject
{
  /**
   * Returns the value of the '<em><b>Key Value Pairs</b></em>' containment reference list.
   * The list contents are of type {@link ingraph.cucumber.featureresult.featureResults.KeyValuePair}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key Value Pairs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key Value Pairs</em>' containment reference list.
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getMapContents_KeyValuePairs()
   * @model containment="true"
   * @generated
   */
  EList<KeyValuePair> getKeyValuePairs();

} // MapContents
