/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Desc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.NodeDesc#getLabels <em>Labels</em>}</li>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.NodeDesc#getPropertyMap <em>Property Map</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getNodeDesc()
 * @model
 * @generated
 */
public interface NodeDesc extends Node
{
  /**
   * Returns the value of the '<em><b>Labels</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Labels</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Labels</em>' attribute list.
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getNodeDesc_Labels()
   * @model unique="false"
   * @generated
   */
  EList<String> getLabels();

  /**
   * Returns the value of the '<em><b>Property Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property Map</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Map</em>' containment reference.
   * @see #setPropertyMap(PropertyMap)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getNodeDesc_PropertyMap()
   * @model containment="true"
   * @generated
   */
  PropertyMap getPropertyMap();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.NodeDesc#getPropertyMap <em>Property Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Map</em>' containment reference.
   * @see #getPropertyMap()
   * @generated
   */
  void setPropertyMap(PropertyMap value);

} // NodeDesc
