/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends FeatureValue
{
} // Node
