/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.PathBody#getNode <em>Node</em>}</li>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.PathBody#getPathLinks <em>Path Links</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPathBody()
 * @model
 * @generated
 */
public interface PathBody extends Path
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference.
   * @see #setNode(NodeDesc)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPathBody_Node()
   * @model containment="true"
   * @generated
   */
  NodeDesc getNode();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.PathBody#getNode <em>Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' containment reference.
   * @see #getNode()
   * @generated
   */
  void setNode(NodeDesc value);

  /**
   * Returns the value of the '<em><b>Path Links</b></em>' containment reference list.
   * The list contents are of type {@link ingraph.cucumber.featureresult.featureResults.PathLink}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path Links</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Links</em>' containment reference list.
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPathBody_PathLinks()
   * @model containment="true"
   * @generated
   */
  EList<PathLink> getPathLinks();

} // PathBody
