/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPath()
 * @model
 * @generated
 */
public interface Path extends Value
{
} // Path
