/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.PathLink#getRelationship <em>Relationship</em>}</li>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.PathLink#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPathLink()
 * @model
 * @generated
 */
public interface PathLink extends EObject
{
  /**
   * Returns the value of the '<em><b>Relationship</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationship</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship</em>' containment reference.
   * @see #setRelationship(EObject)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPathLink_Relationship()
   * @model containment="true"
   * @generated
   */
  EObject getRelationship();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.PathLink#getRelationship <em>Relationship</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationship</em>' containment reference.
   * @see #getRelationship()
   * @generated
   */
  void setRelationship(EObject value);

  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference.
   * @see #setNode(NodeDesc)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPathLink_Node()
   * @model containment="true"
   * @generated
   */
  NodeDesc getNode();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.PathLink#getNode <em>Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' containment reference.
   * @see #getNode()
   * @generated
   */
  void setNode(NodeDesc value);

} // PathLink
