/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.PropertyMap#getMapContents <em>Map Contents</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPropertyMap()
 * @model
 * @generated
 */
public interface PropertyMap extends Map
{
  /**
   * Returns the value of the '<em><b>Map Contents</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Map Contents</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Contents</em>' containment reference.
   * @see #setMapContents(MapContents)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getPropertyMap_MapContents()
   * @model containment="true"
   * @generated
   */
  MapContents getMapContents();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.PropertyMap#getMapContents <em>Map Contents</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map Contents</em>' containment reference.
   * @see #getMapContents()
   * @generated
   */
  void setMapContents(MapContents value);

} // PropertyMap
