/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.RelationshipType#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getRelationshipType()
 * @model
 * @generated
 */
public interface RelationshipType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getRelationshipType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.RelationshipType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // RelationshipType
