/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship Desc</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getType <em>Type</em>}</li>
 *   <li>{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getPropertyMap <em>Property Map</em>}</li>
 * </ul>
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getRelationshipDesc()
 * @model
 * @generated
 */
public interface RelationshipDesc extends Relationship
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(RelationshipType)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getRelationshipDesc_Type()
   * @model containment="true"
   * @generated
   */
  RelationshipType getType();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(RelationshipType value);

  /**
   * Returns the value of the '<em><b>Property Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property Map</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Map</em>' containment reference.
   * @see #setPropertyMap(PropertyMap)
   * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getRelationshipDesc_PropertyMap()
   * @model containment="true"
   * @generated
   */
  PropertyMap getPropertyMap();

  /**
   * Sets the value of the '{@link ingraph.cucumber.featureresult.featureResults.RelationshipDesc#getPropertyMap <em>Property Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Map</em>' containment reference.
   * @see #getPropertyMap()
   * @generated
   */
  void setPropertyMap(PropertyMap value);

} // RelationshipDesc
