/**
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.featureResults;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.cucumber.featureresult.featureResults.FeatureResultsPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends ListElement, PropertyValue
{
} // Value
