/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package ingraph.cucumber.featureresult


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class FeatureResultsRuntimeModule extends AbstractFeatureResultsRuntimeModule {
}
