/*
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.parser.antlr;

import com.google.inject.Inject;
import ingraph.cucumber.featureresult.parser.antlr.internal.InternalFeatureResultsParser;
import ingraph.cucumber.featureresult.services.FeatureResultsGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FeatureResultsParser extends AbstractAntlrParser {

	@Inject
	private FeatureResultsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalFeatureResultsParser createParser(XtextTokenStream stream) {
		return new InternalFeatureResultsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FeatureValue";
	}

	public FeatureResultsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FeatureResultsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
