/*
 * generated by Xtext 2.10.0
 */
package ingraph.cucumber.featureresult.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFeatureResultsScopeProvider extends DelegatingScopeProvider {
}
